spring.datasource.url=jdbc:postgresql://localhost:5433/bicos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=8f3a9c2b1e7d4f6a9b0c123456789abc
